# Site settings | 网站设置
title: Cc-Cece
SEOTitle: Cc-Cece的博客 | Cc-Cece
header-img: img/home-bg-he.png
email: Cc_cece@outlook.com
description: "Cc-Cece的博客"
keyword: "Cc-Cece, Cc-Cece的博客, Python blog"
url: "https://cc-cece.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://cc-cece.github.io/" #code repository | 代码仓库


# Sidebar settings | 侧边栏设置
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "就算这样,也要笑着去努力啊!"
sidebar-avatar: /img/head.jpg      # 头像





# SNS settings | 社交网络设置
#facebook_username: rainbom.z
github_username: Cc-Cece
zhihu_username: Alone993
csdn_username: 958630146




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
# 转换时排除某些文件夹或文件。被排除的文件或文件夹的路径是相对于网站源码目录的，源码目录以外不受影响。
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

Regeneration: true    # 允许文件修改时自动重新生成网站。





# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: true    # 是否开启Gitalk评论
  clientID: 4a1b5da2d73acc06e36a                            #生成的clientID
  clientSecret: 5861502232f3d0c3e5a1e41e6b063c30e8f00484    #生成的clientSecret
  repo: cc-cece.github.io    #仓库名称
  owner: Cc-Cece    # github用户名
  admin: Cc-Cece
  distractionFreeMode: true # 是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 9acee03023ad0c6c993dd86df81e2ac8


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "GitHub·RainbomSea",
        href: "http://RainbomSea.github.io"
    },{
        title: "CSDN·RainbomSea",
        href: "https://blog.csdn.net/qq_39268193"
    },{
        title: "知乎·RainbomSea",
        href: "https://www.zhihu.com/people/RainbomSea"
    },{
        title: "GitBook·RainbomSea",
        href: "https://legacy.gitbook.com/@rainbomsea"
    }
]
