# Site settings | 网站设置
title: WangONC's Blog
SEOTitle: WangONC的博客 | WangONC
header-img: img/home-bg.jpg
email: WangONC@outlook.com
description: "WangONC的博客"
keyword: "WangONC, WangONC的博客, wang, CTF"
url: "http://WangONC.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/WangONC/WangONC.github.io.git" #code repository | 代码仓库


# Sidebar settings | 侧边栏设置
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一只喜欢摄影的RE狗！"
sidebar-avatar: /img/head.jpg      # 头像





# SNS settings | 社交网络设置
facebook_username: WangONC
github_username: WangONC
zhihu_username: WangONC
csdn_username: WangONC




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
# 转换时排除某些文件夹或文件。被排除的文件或文件夹的路径是相对于网站源码目录的，源码目录以外不受影响。
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

Regeneration: true    # 允许文件修改时自动重新生成网站。





# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: true    # 是否开启Gitalk评论
  clientID: be9fef3fbd3b7a4b5d92                            #生成的clientID
  clientSecret: 2092e0764ab4aa10932291e79f726bdfbafa70b3    #生成的clientSecret
  repo: WangONC.github.io    #仓库名称
  owner: WangONC    # github用户名
  admin: WangONC
  #distractionFreeMode: true # 是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: d199cfdda51c1730f66fded558249712


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "GitHub·WangONC",
        href: "http://WangONC.github.io"
    },{
        title: "CSDN·WangONC",
        href: "https://blog.csdn.net/WangONC"
    },{
        title: "知乎·WangONC",
        href: "https://www.zhihu.com/people/WangONC"
    },{
        title: "GitBook·WangONC",
        href: "https://legacy.gitbook.com/xxxxxxxxxxx"
    }
]
